---
- import_tasks: packages.yml
  tags: ubuntu_desktop_packages

- name: Clean up to reduce disk usage
  include_tasks: cleanup.yml
  tags: ubuntu_desktop_cleanup
  when: clean is defined and clean

- meta: flush_handlers
