---

- name: Install ubuntu-desktop (apt)
  become: true
  apt:
    name:
      - ubuntu-desktop
      - python-pip
      - python-dev
      - gcc
    cache_valid_time: 3600

- name: Install packages (pip)
  become: true
  pip:
    name: "psutil"

- name: Start gdm3 service to get a graphical login
  become: true
  service:
    name: gdm3
    state: started

- name: install chromium-browser
  become: true
  apt:
    name: "chromium-browser"
  when: ubuntu_desktop_browser == 'chromium-browser'
